#!/bin/bash

REPOSITORY_URI="https://github.com/moacirosa/git-current-contributors.git"

git clone ${REPOSITORY_URI} ~/.git-current-contributors

echo "### Adding custom git command 'git-current-contributors' @moacirosa" >> ~/.bashrc
echo "export PATH=${PATH}:~/.git-current-contributors" >> ~/.bashrc
echo "export MANPATH=${PATH}:~/.git-current-contributors/man" >> ~/.bashrc

source ~/.bashrc

# Include PATHs for oh-my-zsh as well when it's present

ZSH_FILE=~/.zshrc

if [ -e "$ZSH_FILE" ]
then
  echo "### Adding custom git command 'git-current-contributors' @moacirosa" >> ~/.zshrc
  echo "export PATH=${PATH}:~/.git-current-contributors" >> ~/.zshrc
  echo "export MANPATH=${PATH}:~/.git-current-contributors/man" >> ~/.zshrc
fi

echo "Custom git command 'git-current-contributors' was successfully installed"
echo "Check new command availability by running 'git help -a'"
echo "More info visit ${REPOSITORY_URI}"
